import type { Metadata } from "next";
import { Inter } from "next/font/google";
const inter = Inter({
  subsets: ["latin"],
});
export const metadata: Metadata = {
  description: "Generated by create next app",
  title: "Authentication",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main lang="en">
      <section className={`${inter.className} antialiased`}>{children}</section>
    </main>
  );
}
